version: '2.0'
services:
  weba:
    build: ./frontend
    ports:
        - "3001:3001"
    environment:
        - PORT=3001
        - APIURL=http://localhost:5000
    expose:
        - 3001
    depends_on:
        - server
  webb:
     build: ./frontend
     environment:
         - PORT=3002
     expose:
         - 3002
     depends_on:
          - server

  webc:
     build: ./frontend
     environment:
         - PORT=3003
     expose:
         - 3003
     depends_on:
          - server

  server:
    build: ./backend
    environment:
      - FOLDER=/Users/jackhanley/Downloads/Phone Downloads/Nicole Moudaber's Empty Space Chart/
      - PORT=5000
    ports:
      - "5000:5000"
#  db:
#   build: ./cloudant
#   environment:
#       - PORT=4001
#   ports:
#        - "4001:4001"

  haproxy:
      build: ./haproxy/.
      links:
         - weba
         - webb
      ports:
       - '8080:8080'
